version: '3.8'

services:
  python-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    working_dir: /app
    env_file: .env
    environment:
      - PYTHONUNBUFFERED=1

